export type StudyRoom = {
	id: string;
	building: string;
	roomNumber: string;
	capacity: number;
	features: string[];
	floor: number;
	isQuiet: boolean;
	hasWhiteboard: boolean;
	hasMonitor: boolean;
};

export const STUDY_ROOMS: StudyRoom[] = [
	{
		id: "eng-201",
		building: "Engineering Hall",
		roomNumber: "201",
		capacity: 4,
		features: ["quiet", "whiteboard", "natural light"],
		floor: 2,
		isQuiet: true,
		hasWhiteboard: true,
		hasMonitor: false,
	},
	{
		id: "eng-318",
		building: "Engineering Hall",
		roomNumber: "318",
		capacity: 8,
		features: ["whiteboard", "monitor", "near coffee"],
		floor: 3,
		isQuiet: false,
		hasWhiteboard: true,
		hasMonitor: true,
	},
	{
		id: "eng-410",
		building: "Engineering Hall",
		roomNumber: "410",
		capacity: 12,
		features: ["monitor", "video conferencing", "collaboration tables"],
		floor: 4,
		isQuiet: false,
		hasWhiteboard: false,
		hasMonitor: true,
	},
	{
		id: "lib-b12",
		building: "Main Library",
		roomNumber: "B12",
		capacity: 2,
		features: ["quiet", "individual desks", "sound dampened"],
		floor: -1,
		isQuiet: true,
		hasWhiteboard: false,
		hasMonitor: false,
	},
	{
		id: "lib-104",
		building: "Main Library",
		roomNumber: "104",
		capacity: 6,
		features: ["quiet", "whiteboard", "power outlets"],
		floor: 1,
		isQuiet: true,
		hasWhiteboard: true,
		hasMonitor: false,
	},
	{
		id: "lib-222",
		building: "Main Library",
		roomNumber: "222",
		capacity: 10,
		features: ["monitor", "whiteboard", "near coffee"],
		floor: 2,
		isQuiet: false,
		hasWhiteboard: true,
		hasMonitor: true,
	},
	{
		id: "sci-115",
		building: "Science Center",
		roomNumber: "115",
		capacity: 5,
		features: ["whiteboard", "lab stools", "natural light"],
		floor: 1,
		isQuiet: false,
		hasWhiteboard: true,
		hasMonitor: false,
	},
	{
		id: "sci-207",
		building: "Science Center",
		roomNumber: "207",
		capacity: 7,
		features: ["monitor", "quiet", "near elevator"],
		floor: 2,
		isQuiet: true,
		hasWhiteboard: false,
		hasMonitor: true,
	},
	{
		id: "sci-330",
		building: "Science Center",
		roomNumber: "330",
		capacity: 14,
		features: ["whiteboard", "monitor", "movable seating"],
		floor: 3,
		isQuiet: false,
		hasWhiteboard: true,
		hasMonitor: true,
	},
	{
		id: "bus-140",
		building: "Business School",
		roomNumber: "140",
		capacity: 4,
		features: ["quiet", "near coffee", "power outlets"],
		floor: 1,
		isQuiet: true,
		hasWhiteboard: false,
		hasMonitor: false,
	},
	{
		id: "bus-255",
		building: "Business School",
		roomNumber: "255",
		capacity: 9,
		features: ["whiteboard", "monitor", "conference table"],
		floor: 2,
		isQuiet: false,
		hasWhiteboard: true,
		hasMonitor: true,
	},
	{
		id: "bus-360",
		building: "Business School",
		roomNumber: "360",
		capacity: 16,
		features: ["monitor", "whiteboard", "city view"],
		floor: 3,
		isQuiet: false,
		hasWhiteboard: true,
		hasMonitor: true,
	},
];
